### PR TITLE
Ajive tests

### PR DESCRIPTION
**Pull request by gmischl1**
#### What does this implement/fix? Explain your changes.
Adds some tests for the factorization module to increase code coverage.

### CODE REVIEW

**Comment by gmischl1** [comment]
> Is there some way to see the coverage on PRs?

I feel like we used to have that set up but now we don't. I remember it used to tell you your code coverage change on a PR. I'm not sure what happened to that or how to get it back.

**Comment by gmischl1** [comment]
Going to wait to update this branch and merge it until PR #183 is merged to check if the codecoverage bot works

**Comment by rflperry** [comment]
> Going to wait to update this branch and merge it until PR #183 is merged to check if the codecoverage bot works

Don't think the code coverage bot is working but correct me otherwise

**Comment by gmischl1** [comment]
> > Going to wait to update this branch and merge it until PR #183 is merged to check if the codecoverage bot works
> 
> Don't think the code coverage bot is working but correct me otherwise

Yeah I'm not sure. I also don't know if it only gives an update if you add lines of code that have code coverage themselves. Like since this only added tests I'm not sure it looks at it. I'll try to look more into it later because I'm not sure exactly how it's supposed to behave

**Pull request merged**
